client_id: 813296636721-ap2281oj5m5ip382ekhld12aa5dkobf2.apps.googleusercontent.com
client_secret: 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
developer_token: z27QEhvZe2mjjYFmwwfskg
login_customer_id: 3625606301
refresh_token: 1//03Hwyz46eveQBCgYIARAAGAMSNwF-L9Ir9cv5LfoHVykDpLXg0dKQ-r7NcYd0pkLqXKDE2uXxT4IsGeaJT9pOSPHoAVl92b_pipY
spreadsheet_url: https://docs.google.com/spreadsheets/d/1d6nSLFPgv28D-Ry18r-YSH1Zv9iBTz1ZbViJT2D0WEM/edit?resourcekey=0-hdKLYkBP7YLXEaiP-K6UqQ#gid=0
use_proto_plus: true
