client_id: 813296636721-ap2281oj5m5ip382ekhld12aa5dkobf2.apps.googleusercontent.com
client_secret: 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
developer_token: z27QEhvZe2mjjYFmwwfskg
login_customer_id: '6368728866'
refresh_token: 1//03FPNIW2QgiEsCgYIARAAGAMSNwF-L9Ira0stwlKJFQAVzDDTtY3mV6zmCAiDWC0TDmL-OMMmnYNvMqQwcDqfCqJxEKIyVc6fieE
spreadsheet_url: https://docs.google.com/spreadsheets/d/121COMaz3W9YVDXsOA-N9JN3Si85La0d2E6ulucg2qR8/edit?ouid=108100725051236684502
use_proto_plus: true
valid_config: true
